# Generated by Django 3.2.5 on 2022-11-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('od', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedetail',
            name='destination',
            field=models.CharField(default='NA', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridedetail',
            name='source',
            field=models.CharField(default=0, max_length=264),
            preserve_default=False,
        ),
    ]
